version: '3.6'

services:
  db:
    image: postgres:10.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432

  django:
    build: .
    command: python /app/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - LOCAL_REPO_PATH:/repos
    ports:
      - 8000:8000
    depends_on:
      - db

volumes:
  postgres_data:
